spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create // !주의 이 옵션은 애플리케이션 실행 시점에 테이블 drop 하고, 다시 생성한다.

#로그 레벨
#logging:
#  level: debug
