spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        generate-ddl : false
        open-in-view: false
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
